### ISSUE TITLE
Issue with API calls authentication

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#234]
Two problems were found connected with this subject:
- [x] after deployment to dev environment (and destroying the whole database) the user was still logged in the application (I didn't ask for log in again)
- [ ] As visible on the screenshot below some components are rendered as no data - f.e. the overbooked documents, I should not see them at all if I'm not authorised.
![Screen Shot 2019-04-04 at 11 47 23](https://user-images.githubusercontent.com/38131488/55554493-3186e600-56e3-11e9-8b5f-242645290ce9.png)

**Comment by equadon** [comment]
The issue with still being logged in after a db destroy was because the session ids are stored in Redis and the cookie still matches the session id. After re-deploying Redis the user is logged out.

I was unable to replicate the second point but if this problem still persists we should re-open this ticket. The widgets that are not implemented will be showing but they won't show any actual data.
