### ISSUE TITLE
Volumes and series structure and handling

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#255]
- [ ] Design the solution of storing the volumes with taken into an account migration rules (check cds-dojson repository)
- [ ] Implement the solution with schema, and handling the volumes in the backend

**Comment by equadon** [comment]
### To discuss
- [ ] How do we handle multi-volume records (call them collections or is there a better name?) https://cds.cern.ch/record/2307020?ln=en
- [ ] Can a series and a collection have the same name?
- [ ] **Difficult record**: https://cds.cern.ch/record/2654790?ln=en How do we handle a collection record with multiple series, multiple volumes and has another edition (which has a different number of volumes)?

### Solution 1
Use nested `Series` record. A `Document` can have multiple `Series` and each series can have multiple parent `Series`. The series form a hierarchy we can traverse.
**Problem**: What happens if a sub-series has the same name as a `Series`? We can no longer uniquely identify it so how do we add items to a given series if that happens? **Solution:** Composite keys with `series.title` and `series.series_type` where `series_type` can be `MAIN_SERIES` or `COLLECTION`.

### Solution 2
Store data the same way CDS does it, e.g. a `Document` can have one more volumes and ISBNs for each volume. Mixed items with different volumes in `Document`.

### Solution 3
Create two new records: `Series` and `Collection` where each `Document` can have one or more series and one (or more?) collections.

**Comment by equadon** [comment]
Volumes & series meeting with library (02/05/2019):

- A series consists of multi-volumes and documents
- A multi-volume record consists of documents
- Both documents and multi-volumes can have editions
- A series is for now just a string that both documents and multi-volumes can have
- ISSN not needed but not sure if we might need more metadata for series in the future
- Multi-volumes cannot be loaned and doesn't have ISBNs
- No need to support multi-volumes inside multi-volumes
- Usually users don't search for a document by series unless it's a periodical but we'll still support searching by series for both
- Documents should be searchable by multi-volume

**Comment by kpsherva** [comment]
Comment from the Library:  Multipart monograph series can have ISBN 
Finally decided:
1. Create a record type series with mode of issuance field which indicates if the series in continuous or not
2. Resolve references to series in document JSON
3. Series in the front office are displayed as a search list. In the back office it needs views to manage them
4. Document detail page displays a link to the whole series (search page) and info about the series if any other than title
5. We don't need frontpage series details page, also we don't search specifically in the series index, but in the `series` field of the document
6. Series field is an array in the document.
7. we don't nest series - it introduces too much complexity.

This task has been split for subtasks.
