### ISSUE TITLE
Document Search

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#262]
- [x] The end user should be able to sort by:
  - [x] number of loans
  - [x] number of available items

- [x] The end user should be able to filter (facet) by:
  * has at least a physical copy
  * has an e-book
  * has no copies
- [x] Available items
  * not sure what available means 
  * in the list of results, I see a col. "Items" but I am not sure it corresponds to the sorting. The col. label should match with the sorting value
- [ ] Most loaned
   - [x] Display number of loans
   - [ ] Respect default values for sort order `asc`, `desc`

https://codimd.web.cern.ch/0p-ZhZDnTAycgWGNULBXBQ#UC-User-can-sort-record-search-results-based-on-circulation-information
https://codimd.web.cern.ch/0p-ZhZDnTAycgWGNULBXBQ#UC-FilterSort-search-results-facets

requires #324

**Comment by ntarocco** [comment]
@topless I am re-opening this issue because it is not complete. While the functionality is (hopefully) working correctly, when sorting by:
- [ ] Available items
  * not sure what available means 
  * in the list of results, I see a col. "Items" but I am not sure it corresponds to the sorting. The col. label should match with the sorting value
- [ ] Most loaned
  * when sorting, I cannot see the number of loans as a col, so I cannot understand if I am sorting correctly
