### ISSUE TITLE
refactor: ResultsTable component

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-ils#337]
[Here](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/ui/src/invenio_app_ils/common/components/ResultsTable/ResultsTableBody.js#L33) we need to check if the value is boolean and handle it differently as if the value of the column is false it returns `-` and also when is true the value is not displayed correctly.

**Comment by topless** [comment]
Instead of each list component to explicitly implement ResultsTable, with a custom formatter, create common components per model entity, `LoansTable`, `DocumentTable` which would encapsulate the formatters.

This issue should also address #407. We can provide two lists of properties to the about to be rendered table. A list with the required properties that are used for the internals of the components (i.e. ID), and a list of properties we want to display in the table.

- [ ] Items
- [ ] Loans
- [ ] Document
- [ ] DocumentRelations
- [ ] DocumentRequests
- [ ] EItems
- [ ] Location
- [ ] InternalLocation
- [ ] Patrons
- [ ] Series
- [ ] Related

> note: all the ResultLists have to align with *Table terminology -> ported to common concrete tables.
