### ISSUE TITLE
Back-office ui: create loan details page

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#67]
Implement loan details page as in the mockups.

**Comment by topless** [comment]
Requires #94

**Comment by topless** [comment]
Requires #94

**Comment by topless** [comment]
- [ ] loan record `json` response in links does not include `self`
- [x] for pending loans, `LoanAvailableItems` component
- [x] for running loans, `LoanItem` component displaying information on loaned item
- [x] address loan actions
- [x] ~~resolve `item_pid`, `pickup_location_pid`, `transaction_location_pid`, `transaction_user_pid` to their actual objects~~

**Comment by topless** [comment]
While working on loan details page, I came across an issue which should be addressed.

**The story** is when fetching the loan it comes with an `item_id`. In order to present relevant information of the item we have to fetch the actual record. In that step we have two options:
1) we fire a request from the front end to fetch the entity or 
2) we create a `$ref` property in the loan and a json ref resolver to replace it with the actual item record. 

The benefit of the second approach apart from the extraneous requests (we might need to resolve more type of records), is that if we resolve it we are also able to index it in elastic search.

**The hidden circular dependencies problem** was not visible straight away due to the fact that we were calling `item.replace_refs()` because the item has also `$refs` and then we were calling `loan.replace_refs()` which had an item with resolved refs inside it. This was preventing the circulation problem to show up and instead threw a Python copy error for failing to deep copy objects.

**The actual problem** raises from the fact that the `item` has a property called `circulation_status` (which represents a loan) and the loan has an item, so they are point one another.

**Proposed solution** is to index everything on the item. It might feel a bit "slow" firing extra requests on the front end but like this, we leave circulation isolated without the hassle of overriding methods that resolve records from other services and we keep all our business logic to ils. As it concerns indexing we had a conversation with @zzacharo and we believe that in the worst case we will have to do an extra db query to fetch the record with the id we are looking for.

I might be missing something obvious or not but is there a case that `item -> loan` reference cannot address and we need `loan -> item` relation? @ntarocco, @kprzerwa, @ludmilamarian ?

In case you want to test, experiment or whatever the following branches contain the solution with the $ref.

Branches with circular dependencies: [invenio-app-ils](https://github.com/topless/invenio-app-ils/tree/67-circular-dependencies), [invenio-circulation](https://github.com/topless/invenio-circulation/tree/67-circular-dependencies)

**Update**: After a short talk with the team, we will have to explore further and agree on how we will structure our models and their dependencies. Something we tried out with @zzacharo and actually worked, is to manually [remove](https://github.com/topless/invenio-app-ils/blob/9319cd6dd44a3a9a9d98d21b39a1560c43eba6f7/invenio_app_ils/circulation/utils.py#L35) the `circulation_status` from the item when it gets resolved by a `loan`. Either way I have a branch with each one of the aforementioned solutions (1 and 2) on top.

I will also tag @ntarocco for his feedback since he loves manual manipulations on models.

**Comment by topless** [comment]
![Screenshot 2019-01-08 01.19.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb4d56ac57528001274a12b/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e795ce37b21cbb271f1122f43434d0eee1e020a17b8eb8339a3e53d778d5c03ebd838097cc63b11acbed14dbe02bf21d95d99a4fedb1294b7607caddecd5d340c041083fe5831a6904bce50f54ae24b56b65e.png)

**Comment by ntarocco** [comment]
@topless nice writing here, thanks for the detailed explanations! 
I agree with the solution!
