### ISSUE TITLE
Make sure the views are correctly protected via permissions

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#884]
check the different record endpoints / different request methods
check the custom endpoints

**Comment by ntarocco** [comment]
The best thing to do is probably to add unit test for all the endpoints and verify permissions.

**Comment by FlorianCassayre** [comment]
I'm documenting the process along the way because we might have to do it again later on. To list all the endpoints registered in the current app, simply do:
```Python
from flask import current_app

print(current_app.url_map)
```
This is crucial since we can then exhaustively review all of them without missing any. Note that this will also list endpoints registered by other invenio services. We are only interested in testing the ones we defined in ILS _and_ the endpoints to which we may have applied modifications (typically circulation). The CRUD record endpoints are dynamically generated by `invenio-records-rest` and we must verify these as well.

The same process should be done in CDS-ILS, for the endpoints defined there.

In the current version of ILS I found the following endpoints which were insufficiently tested for permissions (ie. missing test case for patron user), or not tested at all:
* [x] `/internal-locations/*`, `invenio_records_rest.ilocid_*`
* [x] ~`/circulation/loans/<pid_value>/<action>`, `invenio_circulation_loan_actions.loanid_actions`~
* [x] `/circulation/loans/<pid_value>/email-overdue`, `invenio_app_ils_circulation.loanid_email`
* [x] ~`/circulation/loans/<pid_value>/replace-item`, `invenio_circulation_loan_replace_item.loan_replace_item_resource`~
* [x] `/circulation/loans/<pid_value>/update-dates`, `invenio_app_ils_circulation.loanid_update_dates`
* [x] `/circulation/stats/most-loaned`, `invenio_app_ils_circulation_stats.most-loaned`
* [ ] `/documents/<pid_value>/relations`, `invenio_app_ils_relations.docid_relations`
* [x] ~`/documents/<pid_value>/stats`, `ils_document_stats.docid_stats`~
* [x] ~`/eitems/<pid_value>/stats`, `ils_document_stats.eitmid_stats`~
* [x] ~`/literature/*`, `invenio_records_rest.litid_*`~
* [x] `/locations/*`, `invenio_records_rest.locid_*`
* [x] `/patrons/*`, `invenio_records_rest.patid_*`
* [ ] `/series/<pid_value>/relations`, `invenio_app_ils_relations.serid_relations`
* [x] ~`/series/<pid_value>/stats`, `ils_document_stats.serid_stats`~
* [x] `/vocabularies/*`, `invenio_records_rest.vocid_*`

CDS-ILS only has `/importer/*`, which is already protected by permissions (but untested).

(in each line the first value is the endpoint url, while the second one is the view name. The wildcards mean there are several related endpoints)

There might be false positives.
I'll address the true positives in a PR.
