### ISSUE TITLE
SQLAlchemy-Utils version issue

### ISSUE THREAD

**Issue by kvslee** [inveniosoftware/invenio-app-ils#896]
Running ./scripts/bootstrap throws errors relating to SQLAlchemy-Utils. 

ERROR: invenio-db 1.0.5 has requirement SQLAlchemy-Utils<0.36,>=0.33.1, but you'll have sqlalchemy-utils 0.36.6 which is incompatible.
ERROR: invenio-oauth2server 1.2.0 has requirement SQLAlchemy-Utils[encrypted]<0.36.0,>=0.33.0, but you'll have sqlalchemy-utils 0.36.6 which is incompatible.

I am using Python 3.6.10.

**Comment by kvslee** [comment]
I downgraded SQLAlchemy-Utils in my Python packages to match the required version.

**Comment by ntarocco** [comment]
Sorry @kvslee, please feel free to mention us in the issues because I honestly missed your issues! :( Apologies...
We did not notice this issue: we have Travis building every day the environment and it was not reported. Did you install it in a different way?
Let us know if you still encounter the issue.

**Comment by kpsherva** [comment]
closing issue as stale
